#数据库连接配置
spring:
  profiles:
    active: jdbc, redis, mail
  #配置thymeleaf渲染视图
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
    cache: false  # 关闭缓存
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#  使用mybatis配置文件时需要指明
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
# 指定sql映射文件位置
 mapper-locations: classpath:com/zsc/finance/mapper/*.xml

# spring boot集成mybatis的方式打印sql语句
# configuration:
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  #端口设置
  port: 8080
  servlet:
    session:
      #session超时时间设置：2小时 7200秒
      timeout: PT2H


